var searchData=
[
  ['u16streampos_0',['u16streampos',['http://en.cppreference.com/w/cpp/io/fpos.html',1,'std']]],
  ['u16string_1',['u16string',['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std::pmr::u16string'],['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std::u16string']]],
  ['u16string_5fview_2',['u16string_view',['http://en.cppreference.com/w/cpp/experimental/basic_string_view.html',1,'std::experimental::u16string_view'],['http://en.cppreference.com/w/cpp/string/basic_string_view.html',1,'std::u16string_view']]],
  ['u32streampos_3',['u32streampos',['http://en.cppreference.com/w/cpp/io/fpos.html',1,'std']]],
  ['u32string_4',['u32string',['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std::pmr::u32string'],['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std::u32string']]],
  ['u32string_5fview_5',['u32string_view',['http://en.cppreference.com/w/cpp/experimental/basic_string_view.html',1,'std::experimental::u32string_view'],['http://en.cppreference.com/w/cpp/string/basic_string_view.html',1,'std::u32string_view']]],
  ['u8string_6',['u8string',['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std::pmr::u8string'],['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std::u8string']]],
  ['u8string_5fview_7',['u8string_view',['http://en.cppreference.com/w/cpp/string/basic_string_view.html',1,'std']]],
  ['uint16_5ft_8',['uint16_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint32_5ft_9',['uint32_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint64_5ft_10',['uint64_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint8_5ft_11',['uint8_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5ffast16_5ft_12',['uint_fast16_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5ffast32_5ft_13',['uint_fast32_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5ffast64_5ft_14',['uint_fast64_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5ffast8_5ft_15',['uint_fast8_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5fleast16_5ft_16',['uint_least16_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5fleast32_5ft_17',['uint_least32_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5fleast64_5ft_18',['uint_least64_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5fleast8_5ft_19',['uint_least8_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uintmax_5ft_20',['uintmax_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uintptr_5ft_21',['uintptr_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['unary_5ffunction_22',['unary_function',['http://en.cppreference.com/w/cpp/utility/functional/unary_function.html',1,'std']]],
  ['unary_5fnegate_23',['unary_negate',['http://en.cppreference.com/w/cpp/utility/functional/unary_negate.html',1,'std']]],
  ['underflow_5ferror_24',['underflow_error',['http://en.cppreference.com/w/cpp/error/underflow_error.html',1,'std']]],
  ['underlying_5ftype_25',['underlying_type',['http://en.cppreference.com/w/cpp/types/underlying_type.html',1,'std']]],
  ['underlying_5ftype_3c_20enum_5ftype_20_3e_26',['underlying_type&lt; enum_type &gt;',['http://en.cppreference.com/w/cpp/types/underlying_type.html',1,'std']]],
  ['underlying_5ftype_5ft_27',['underlying_type_t',['http://en.cppreference.com/w/cpp/types/underlying_type.html',1,'std']]],
  ['unexpect_5ft_28',['unexpect_t',['../structgpcl_1_1unexpect__t.html',1,'gpcl']]],
  ['unexpected_29',['unexpected',['../classgpcl_1_1unexpected.html',1,'gpcl']]],
  ['unexpected_5fhandler_30',['unexpected_handler',['http://en.cppreference.com/w/cpp/error/unexpected_handler.html',1,'std']]],
  ['uniform_5fint_5fdistribution_31',['uniform_int_distribution',['http://en.cppreference.com/w/cpp/numeric/random/uniform_int_distribution.html',1,'std']]],
  ['uniform_5freal_5fdistribution_32',['uniform_real_distribution',['http://en.cppreference.com/w/cpp/numeric/random/uniform_real_distribution.html',1,'std']]],
  ['unique_5fhandle_33',['unique_handle',['../classgpcl_1_1detail_1_1unique__handle.html',1,'gpcl::detail']]],
  ['unique_5fhandle_3c_20mqd_5ftraits_20_3e_34',['unique_handle&lt; mqd_traits &gt;',['../classgpcl_1_1detail_1_1unique__handle.html',1,'gpcl::detail']]],
  ['unique_5fhandle_3c_20pid_5ftraits_20_3e_35',['unique_handle&lt; pid_traits &gt;',['../classgpcl_1_1detail_1_1unique__handle.html',1,'gpcl::detail']]],
  ['unique_5flock_36',['unique_lock',['../classgpcl_1_1unique__lock.html',1,'gpcl::unique_lock&lt; MutexType &gt;'],['http://en.cppreference.com/w/cpp/thread/unique_lock.html',1,'std::unique_lock']]],
  ['unique_5flock_5fguard_37',['unique_lock_guard',['../structgpcl_1_1detail_1_1posix__pid__file_1_1unique__lock__guard.html',1,'gpcl::detail::posix_pid_file']]],
  ['unique_5fptr_38',['unique_ptr',['../classgpcl_1_1unique__ptr.html',1,'gpcl::unique_ptr&lt; T, Deleter &gt;'],['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std::unique_ptr']]],
  ['unique_5fptr_3c_20bfd_2c_20bfd_5fdeleter_20_3e_39',['unique_ptr&lt; bfd, bfd_deleter &gt;',['../classgpcl_1_1unique__ptr.html',1,'gpcl']]],
  ['unique_5fptr_3c_20t_2c_20gpcl_3a_3adetail_3a_3aref_5fcount_5fobj_3a_3adestroy_20_3e_40',['unique_ptr&lt; T, gpcl::detail::ref_count_obj::destroy &gt;',['../classgpcl_1_1unique__ptr.html',1,'gpcl']]],
  ['unique_5fptr_3c_20t_5b_5d_2c_20deleter_20_3e_41',['unique_ptr&lt; T[], Deleter &gt;',['../classgpcl_1_1unique__ptr_3_01T_0f_0e_00_01Deleter_01_4.html',1,'gpcl']]],
  ['unordered_5fmap_42',['unordered_map',['http://en.cppreference.com/w/cpp/container/unordered_map.html',1,'std::pmr::unordered_map'],['http://en.cppreference.com/w/cpp/container/unordered_map.html',1,'std::unordered_map']]],
  ['unordered_5fmap_3c_20fbase_5faddress_2c_20gpcl_3a_3adetail_3a_3abfd_5fcache_20_3e_43',['unordered_map&lt; fbase_address, gpcl::detail::bfd_cache &gt;',['http://en.cppreference.com/w/cpp/container/unordered_map.html',1,'std']]],
  ['unordered_5fmultimap_44',['unordered_multimap',['http://en.cppreference.com/w/cpp/container/unordered_multimap.html',1,'std::pmr::unordered_multimap'],['http://en.cppreference.com/w/cpp/container/unordered_multimap.html',1,'std::unordered_multimap']]],
  ['unordered_5fmultiset_45',['unordered_multiset',['http://en.cppreference.com/w/cpp/container/unordered_multiset.html',1,'std::pmr::unordered_multiset'],['http://en.cppreference.com/w/cpp/container/unordered_multiset.html',1,'std::unordered_multiset']]],
  ['unordered_5fset_46',['unordered_set',['http://en.cppreference.com/w/cpp/container/unordered_set.html',1,'std::pmr::unordered_set'],['http://en.cppreference.com/w/cpp/container/unordered_set.html',1,'std::unordered_set']]],
  ['unsequenced_5fpolicy_47',['unsequenced_policy',['http://en.cppreference.com/w/cpp/algorithm/execution_policy_tag_t.html',1,'std::execution']]],
  ['unsynchronized_5fpool_5fresource_48',['unsynchronized_pool_resource',['http://en.cppreference.com/w/cpp/experimental/unsynchronized_pool_resource.html',1,'std::experimental::pmr::unsynchronized_pool_resource'],['http://en.cppreference.com/w/cpp/memory/unsynchronized_pool_resource.html',1,'std::pmr::unsynchronized_pool_resource']]],
  ['unwrap_5fref_5fdecay_49',['unwrap_ref_decay',['http://en.cppreference.com/w/cpp/utility/functional/unwrap_reference.html',1,'std']]],
  ['unwrap_5fref_5fdecay_5ft_50',['unwrap_ref_decay_t',['http://en.cppreference.com/w/cpp/utility/functional/unwrap_reference.html',1,'std']]],
  ['unwrap_5freference_51',['unwrap_reference',['http://en.cppreference.com/w/cpp/utility/functional/unwrap_reference.html',1,'std']]],
  ['uses_5fallocator_52',['uses_allocator',['http://en.cppreference.com/w/cpp/memory/uses_allocator.html',1,'std']]]
];
