add_executable (auto_linking main.cpp)
target_include_directories (auto_linking PRIVATE ${GPCL_SOURCE_DIR})
target_compile_definitions (auto_linking PRIVATE GPCL_SEPARATE_COMPILATION=1)
target_link_directories (auto_linking PRIVATE ${CMAKE_LIBRARY_OUTPUT_DIRECTORY})
add_dependencies (auto_linking gpcl::separate)
