//
// gpcl.hpp
// ~~~~~~~~
//
// Copyright (c) 2020-2022 Zhengyi Fu (tsingyat at outlook dot com)
//
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
//

#ifndef GPCL_HPP
#define GPCL_HPP

#include <gpcl/access_mode.hpp>
#include <gpcl/allocate_shared.hpp>
#include <gpcl/anonymous_shared_memory.hpp>
#include <gpcl/any.hpp>
#include <gpcl/any_cast.hpp>
#include <gpcl/apply.hpp>
#include <gpcl/array.hpp>
#include <gpcl/assert.hpp>
#include <gpcl/bad_any_cast.hpp>
#include <gpcl/bad_expected_access.hpp>
#include <gpcl/bad_weak_ptr.hpp>
#include <gpcl/basic_any.hpp>
#include <gpcl/basic_osyncstream.hpp>
#include <gpcl/basic_spanbuf.hpp>
#include <gpcl/basic_spanstream.hpp>
#include <gpcl/basic_stacktrace.hpp>
#include <gpcl/basic_syncbuf.hpp>
#include <gpcl/bind_front.hpp>
#include <gpcl/buffer.hpp>
#include <gpcl/buffer_iterator.hpp>
#include <gpcl/buffer_sequence.hpp>
#include <gpcl/buffer_size.hpp>
#include <gpcl/buffer_to_string.hpp>
#include <gpcl/buffers_range_ref.hpp>
#include <gpcl/clock.hpp>
#include <gpcl/clone_ptr.hpp>
#include <gpcl/condition_variable.hpp>
#include <gpcl/const_buffer.hpp>
#include <gpcl/content_iterator.hpp>
#include <gpcl/creation_tag.hpp>
#include <gpcl/debugstream.hpp>
#include <gpcl/decay_copy.hpp>
#include <gpcl/default_allocator.hpp>
#include <gpcl/enable_shared_from.hpp>
#include <gpcl/enable_shared_from_this.hpp>
#include <gpcl/error.hpp>
#include <gpcl/error_info.hpp>
#include <gpcl/event.hpp>
#include <gpcl/exception.hpp>
#include <gpcl/excfwd.hpp>
#include <gpcl/expected.hpp>
#include <gpcl/expected_fwd.hpp>
#include <gpcl/file.hpp>
#include <gpcl/function.hpp>
#include <gpcl/function_ref.hpp>
#include <gpcl/future.hpp>
#include <gpcl/generic_pointer_cast.hpp>
#include <gpcl/get_deleter.hpp>
#include <gpcl/getopt.hpp>
#include <gpcl/in_place.hpp>
#include <gpcl/in_place_type.hpp>
#include <gpcl/intrusive_list.hpp>
#include <gpcl/intrusive_ptr.hpp>
#include <gpcl/inttypes.hpp>
#include <gpcl/invoke.hpp>
#include <gpcl/is_basic_lockable.hpp>
#include <gpcl/is_lockable.hpp>
#include <gpcl/ispanstream.hpp>
#include <gpcl/iterator_range.hpp>
#include <gpcl/json.hpp>
#include <gpcl/json_at.hpp>
#include <gpcl/json_cast.hpp>
#include <gpcl/json_error.hpp>
#include <gpcl/json_index.hpp>
#include <gpcl/json_iomanip.hpp>
#include <gpcl/json_size.hpp>
#include <gpcl/json_tag.hpp>
#include <gpcl/lexical_cast.hpp>
#include <gpcl/lock.hpp>
#include <gpcl/lock_file.hpp>
#include <gpcl/make_any.hpp>
#include <gpcl/make_basic_any.hpp>
#include <gpcl/make_iomanip.hpp>
#include <gpcl/make_shared.hpp>
#include <gpcl/memory_mapped_region.hpp>
#include <gpcl/message_queue.hpp>
#include <gpcl/meta.hpp>
#include <gpcl/meta_fwd.hpp>
#include <gpcl/mutable_buffer.hpp>
#include <gpcl/mutex.hpp>
#include <gpcl/narrow_cast.hpp>
#include <gpcl/noncopyable.hpp>
#include <gpcl/object_pool.hpp>
#include <gpcl/offset_ptr.hpp>
#include <gpcl/once_flag.hpp>
#include <gpcl/optional.hpp>
#include <gpcl/optional_fwd.hpp>
#include <gpcl/ospanstream.hpp>
#include <gpcl/osyncstream.hpp>
#include <gpcl/pid_file.hpp>
#include <gpcl/pool.hpp>
#include <gpcl/pool_allocator.hpp>
#include <gpcl/propagate_const.hpp>
#include <gpcl/scope_exit.hpp>
#include <gpcl/scope_fail.hpp>
#include <gpcl/scope_success.hpp>
#include <gpcl/scoped_array.hpp>
#include <gpcl/scoped_lock.hpp>
#include <gpcl/semaphore.hpp>
#include <gpcl/shared_memory_object.hpp>
#include <gpcl/shared_ptr.hpp>
#include <gpcl/simple_segregated_storage.hpp>
#include <gpcl/span.hpp>
#include <gpcl/spanbuf.hpp>
#include <gpcl/spanstream.hpp>
#include <gpcl/sqlite.hpp>
#include <gpcl/stacktrace.hpp>
#include <gpcl/strerror.hpp>
#include <gpcl/swap.hpp>
#include <gpcl/syncbuf.hpp>
#include <gpcl/tag_invoke.hpp>
#include <gpcl/thread.hpp>
#include <gpcl/thread_attributes.hpp>
#include <gpcl/throw_exception.hpp>
#include <gpcl/time.hpp>
#include <gpcl/type_identity.hpp>
#include <gpcl/typeid.hpp>
#include <gpcl/unexpected.hpp>
#include <gpcl/unique_lock.hpp>
#include <gpcl/unique_ptr.hpp>
#include <gpcl/unique_resource.hpp>
#include <gpcl/variant.hpp>
#include <gpcl/vector.hpp>
#include <gpcl/version.hpp>
#include <gpcl/weak_ptr.hpp>
#include <gpcl/zstring.hpp>

#endif // GPCL_HPP
